permissions:
  BUILD:
    1:
      types: block-break,block-place
    2:
      types: entity-interact
      entities: ARMOR_STAND,GLOW_ITEM_FRAME,ITEM_FRAME,PAINTING
    3:
      types: block-interact
      items: FLINT_AND_STEEL,FIRE_CHARGE

  VEHICLE:
    1:
      types: block-interact
      items: MINECART,CHEST_MINECART,COMMAND_BLOCK_MINECART,FURNACE_MINECART,HOPPER_MINECART,TNT_MINECART
    2:
      types: block-interact
      items: OAK_BOAT,BIRCH_BOAT,DARK_OAK_BOAT,SPRUCE_BOAT,ACACIA_BOAT,JUNGLE_BOAT
    3:
      types: entity-interact
      entities: MINECART,CHEST_MINECART,COMMAND_BLOCK_MINECART,FURNACE_MINECART,HOPPER_MINECART,TNT_MINECART
    4:
      types: entity-interact
      entities: OAK_BOAT,BIRCH_BOAT,DARK_OAK_BOAT,SPRUCE_BOAT,ACACIA_BOAT,JUNGLE_BOAT

  DOOR:
    1:
      types: block-interact
      blocks: OAK_DOOR,BIRCH_DOOR,DARK_OAK_DOOR,SPRUCE_DOOR,ACACIA_DOOR,JUNGLE_DOOR,CRIMSON_TRAPDOOR,WARPED_TRAPDOOR
    2:
      types: block-interact
      blocks: OAK_TRAPDOOR,BIRCH_TRAPDOOR,DARK_OAK_TRAPDOOR,SPRUCE_TRAPDOOR,ACACIA_TRAPDOOR,JUNGLE_TRAPDOOR,CRIMSON_TRAPDOOR,WARPED_TRAPDOOR
    3:
      types: block-interact
      blocks: OAK_FENCE_GATE,BIRCH_FENCE_GATE,DARK_OAK_FENCE_GATE,SPRUCE_FENCE_GATE,ACACIA_FENCE_GATE,JUNGLE_FENCE_GATE,CRIMSON_FENCE_GATE,WARPED_FENCE_GATE

  SWITCH:
    1:
      type: block-interact
      blocks: OAK_BUTTON,BIRCH_BUTTON,DARK_OAK_BUTTON,SPRUCE_BUTTON,ACACIA_BUTTON,JUNGLE_BUTTON,CRIMSON_BUTTON,WARPED_BUTTON,STONE_BUTTON,POLISHED_BLACKSTONE_BUTTON
    2:
      type: block-interact
      blocks: LEVER

