name: Factionals
main: fly.factions.Factionals
version: 1.0.0
api-version: 1.13
depend: [dynmap]
softdepend: [MagicModule]
commands:
  f:
    description:
  faction:
    description:
  factions:
    description:
  factionals:
    description:
  rtpad:
    description:
  rtpa:
    description:
  rtpc:
    description: