name: Factionals
main: fly.factions.Factionals
version: 1.0.0
api-version: 1.13
commands:
  g:
    description:
  group:
    description:
  f:
    description:
  faction:
    description:
  p:
    description:
  plot:
    description: